Document legacy API that was removed in #64
w3c/webrtc-encoded-transform pull request #111
Opened 2021-07-08 09:31 UTC by alvestrand

Fixes #105

2021-07-08 13:57 UTC, jan-ivar requested changes

2021-07-08 13:57 UTC, jan-ivar commented on index.bs
> +This is still supported by some browsers, and is therefore documented here. Once the
My understanding is this API was never shipped. It was only ever made available under Origin Trial. 

Since the API has been superseded with a new one, Chrome should not ship the old one. Isn't this what origin trials are for?

2021-07-08 14:08 UTC, alvestrand commented
Asking @dontcallmedom for help with the bikeshed reference error.

2021-07-08 15:43 UTC, youennf reviewed
AIUI, the issue is for Chromium to be able to document and refer what is currently being implemented there since some links are now dead.
It seems to me the best way forward is to take the revision of the spec which is closest to what Chromium current implements, add obsolete warning (for instance point to the latest draft of webrtc-encoded-transform), host it in Chromium servers and update Chromium documentation dead links accordingly.

2021-07-08 15:43 UTC, youennf commented on index.bs
> +new API is functionally complete and adopted by all browsers that supported the older API,
This is probably incorrect, the latest API version is more complete than the old version: the old version can be JS shimed by the new version for instance, the reverse is not true.
If I am misunderstanding things, can you provide more details?

2021-07-08 15:43 UTC, youennf commented on index.bs
> +this section will be deleted.
There was consensus in the WG to delete the old version from the spec. I don't see benefits in reviving this discussion.

I also do not see benefits in adding back the old version in the draft. For instance, if adding it back, the natural question would be why the WG moved from the old to the new version and the spec would need to document this. I do not think the spec is the right place for that.

2021-07-08 15:43 UTC, youennf commented on index.bs
> +# Legacy stream accessor API # {#legacy}
Contrary to other legacy API examples, there was no consensus within the WG on the shape of this version of the API. The spec does not seem the right place for describing this particular version of the API.

2021-07-22 01:58 UTC, alvestrand commented on index.bs
> +new API is functionally complete and adopted by all browsers that supported the older API,
Do you have a shim that demonstrates this claim?

2021-07-22 01:58 UTC, alvestrand commented on index.bs
> +# Legacy stream accessor API # {#legacy}
This was the shape of the API at the time of adoption of the document.
What's your alternate proposal for describing this particular version of the API?

2021-07-26 23:06 UTC, youennf commented on index.bs
> +new API is functionally complete and adopted by all browsers that supported the older API,
I can provide an example that would shim createEncodedStreams if that helps. Basically, set a script transform when creating a sender or receiver (so shim addTrack for instance). In the worker, transfer the readable and writable back to the page context. Use identity transforms if needed in the page context in createEncodedStreams shim.

The point though is that you write: "Once the new API is functionally complete."
It seems to indicate the 'new API' is not functionally complete. Can you describe which functionality is missing?

2021-07-26 23:08 UTC, youennf commented on index.bs
> +# Legacy stream accessor API # {#legacy}
As I said above, take a revision of the spec in this repo that is closest to Chromium implementation. Then add some warnings this is no longer active and document we are transitioning to a new API surface.

2021-08-17 07:19 UTC, guidou commented on index.bs
> +# Legacy stream accessor API # {#legacy}
> Contrary to other legacy API examples, there was no consensus within the WG on the shape of this version of the API. The spec does not seem the right place for describing this particular version of the API.

Note that there is no consensus either on the the API as described in the current document.
We initially had no objections, but when we started to plan the implementation in Chromium we consulted developers, and the feedback has been consistently negative. Some of it is public, see https://twitter.com/HCornflower/status/1402227026724114436

Therefore, assume no consensus on any version of this document.

2021-08-17 08:21 UTC, youennf commented on index.bs
> +# Legacy stream accessor API # {#legacy}
> assume no consensus yet on any version of this document.

I was meaning 'consensus during the WebRTC interim room' or at least, as we discussed how to phrase it at last interim, 'no objection during the WebRTC interims'.

> the feedback has been consistently negative.

It would be good to document this feedback and file issues accordingly.

> https://twitter.com/HCornflower/status/1402227026724114436

This particular message is very succinct and I am not sure how to build on it.
It would be good to get a more precise understanding of what the underlying issues are so that we can work on improving the API.

2021-08-17 12:50 UTC, fippo commented on index.bs
> +# Legacy stream accessor API # {#legacy}
> I was meaning 'consensus during the WebRTC interim room' or at least, as we discussed how to phrase it at last interim, 'no objection during the WebRTC interims'.

If you look at the audience of the interims, it is probably not representing the actual API users. Where are the big cpaas providers for example? IMO the WebRTC WG has lost contact with the developers using the APIs a while back (which was one of the reasons I left the WG in 2018). This has not gotten better, on the contrary...

> This particular message is very succinct and I am not sure how to build on it.
> It would be good to get a more precise understanding of what the underlying issues are so that we can work on improving the API.

From a application developer point of view the "legacy" API works and I have no concerns with the general API shape,
just some minor wishes for additional data. It has been proven in the field for quite a while now, with the biggest problem being performance due to locking in the main thread even when processing was done on a worker. That is (was? Guido knows) an implementation problem however.

The lack of developer relations by not providing sample implementations e.g. on [the samples repository](https://webrtc.github.io/samples/src/content/insertable-streams/endtoend-encryption/) is probably unhelpful for adoption too. See above wrt not being in touch with the users of the API (which also applies to the general state of that repository and others in the webrtc github organisation)

2021-08-17 13:56 UTC, youennf commented on index.bs
> +# Legacy stream accessor API # {#legacy}
> That is (was? Guido knows) an implementation problem however.

I believe this is a model issue. The new spec is making it easier to get it right.

> The lack of developer relations by not providing sample implementations e.g. on [the samples repository](https://webrtc.github.io/samples/src/content/insertable-streams/endtoend-encryption/) is probably unhelpful for adoption too.

Good point, I'll look at updating the sample code to make it work with current Safari Tech Preview implementation.
This will show the necessary code to transition from one API to the other, that should not be big.
Is there anything else you have in mind that might help?

2021-08-17 13:58 UTC, youennf commented on index.bs
> +# Legacy stream accessor API # {#legacy}
> Good point, I'll look at updating the sample code

https://github.com/webrtc/samples/issues/1467

2021-08-17 18:05 UTC, aboba commented
Do we need a Call for Consensus on this PR?

2022-07-27 14:06 UTC, fippo commented
This API should also disallow modification of the `encodedInsertableStreams` via setParameters by throwing an InvalidModificationError

2022-12-01 15:32 UTC, youennf commented
Should we add the IceBox label?

2024-08-01 14:15 UTC, alvestrand commented
No consensus to merge; this seems unlikely to change soon. Closing.

2024-08-01 14:15 UTC, closed without merging