Use unsigned long instead of long for positive values
w3c/webrtc-encoded-transform pull request #126
Opened 2021-12-07 13:09 UTC by dontcallmedom

webkit implementation already uses unsigned long for some of these https://github.com/WebKit/WebKit/blob/5858e9511bb3d3306db3c4bc0973c521cdc97a03/Source/WebCore/Modules/mediastream/RTCEncodedVideoFrame.idl

2022-07-07 14:56 UTC, jan-ivar commented
@dontcallmedom is there some design guidance here on unsigned? I only found [§ 8.1. Use numeric types appropriately](https://w3ctag.github.io/design-principles/#promises-and-events) which doesn't say.

My purely personal preference is unsigned for ids and signed for any scalar values like width and height, where > and < may be used, as I've seen bugs from code doing 0 < n or math that ends with bugs because they suddenly get a giant value.

2022-07-07 14:58 UTC, alvestrand commented
Needs text for what the values mean (below the IDL).

2022-10-04 19:08 UTC, fippo requested changes
needs rebase (sorry)

2022-10-05 07:07 UTC, dontcallmedom commented on index.bs
>      sequence&lt;long long&gt; dependencies;
fixed in f50263e

2022-10-05 07:08 UTC, dontcallmedom commented on index.bs
> +  sequence&lt;unsigned long&gt; contributingSources;
since this is no longer about tweaking IDL types, it feels to me that this should be brought up in a separate issue

2022-10-05 08:16 UTC, fippo commented on index.bs
> +  sequence&lt;unsigned long&gt; contributingSources;
#157

2022-12-01 15:42 UTC, youennf commented
spatialIndex and temporalIndex being unsigned seem to align with WebCodecs.

2022-12-01 15:52 UTC, youennf approved these changes

2022-12-08 15:37 UTC, merged