make generateKeyFrame take a list of rids and return void
w3c/webrtc-encoded-transform pull request #165
Opened 2022-11-29 11:03 UTC by fippo

making it request a key frame for each rid or all of them if the list is empty.

Returning a promise resolving with a timestamp is not necessary since requesting a key frame is something the encoder might not be able or willing to satisfy.

2022-11-29 11:27 UTC, fippo commented
discussed at the October 2022 meeting: https://www.w3.org/2022/10/18-webrtc-minutes.html#t03

2022-12-08 15:52 UTC, alvestrand commented
Discussed at the December meeting. Needs update to return promise<undefined>.

2022-12-14 09:09 UTC, fippo commented
updated. @dontcallmedom will need to slap the IPR bot who seems to have forgotten we're friends again ;-)

2022-12-15 15:39 UTC, youennf commented on index.bs
> +1. Resolve |promise| with `undefined`.
I think we want to resolve the promise when the key frame is being queued, this is what the current spec is asking and is a nice addition in the case of script transform.

2022-12-16 08:55 UTC, solmaks commented on index.bs
> +1. Resolve |promise| with `undefined`.
This will introduce unnecessary complexity to what was supposed to be as a simple key frame generation mechanism. And will make scenarios involving multiple streams (active, inactive, restricted) not only hard to define in specification, but even more harder to implement in user agents.

2022-12-16 10:37 UTC, youennf commented on index.bs
> +1. Resolve |promise| with `undefined`.
This complexity is fairly limited in the case of script transform, please have a look at how this is already implemented in WebKit.
For the sender API, I agree the usefulness is reduced, we could consider relaxing the resolution timing if it proves difficult to implement.

> not only hard to define in specification

This is already defined in the spec for the script transform code path.

2022-12-27 09:58 UTC, fippo commented on index.bs
> +1. Resolve |promise| with `undefined`.
I don't think anyone considered awaiting useful at [TPAC](https://lists.w3.org/Archives/Public/public-webrtc/2022Sep/0046.html), to quote the minutes:
> this can be done by waiting to a keyframe in the  stream before doing the key change"

With multiple rids when do you resolve?
On the first keyframe (regardless of layer) or do you wait for all of them? Return an array of promises?
What about cases like turning off the lowest simulcast layer and asking for a keyframe? Surprise (thankfully not returning an RTP timestamp you don't expect anymore). 
What if the highest layer is disabled due to bandwidth restrictions?

2023-01-05 15:41 UTC, youennf commented on index.bs
> +1. Resolve |promise| with `undefined`.
> On the first keyframe (regardless of layer) or do you wait for all of them? Return an array of promises?

On the first keyframe of any layer would make sense.

2023-01-05 15:52 UTC, alvestrand commented on index.bs
> +1. Resolve |promise| with `undefined`.
1) this should happen in a "queue a task" or "in parallel", so that it's obviously async
2) we should guarantee that the promise resolves before the first of the keyframes arrives at the transform.

2023-01-05 15:52 UTC, jan-ivar requested changes

2023-01-05 15:52 UTC, jan-ivar commented on index.bs
> +1. Run the [=generate key frame algorithm=] with |promise|, |this| and |rids|.
This patch removes [in-parallel](https://html.spec.whatwg.org/multipage/infrastructure.html#in-parallel), making this algorithm synchronous while still returning a promise, which is an anti-pattern.

We'd need to either restore in-parallel or drop the promise, for this to make sense.

2023-01-10 10:49 UTC, fippo commented on index.bs
> +1. Resolve |promise| with `undefined`.
What usecase does resolving on a "random" keyframe solve? Also how do you avoid this keyframe being triggered by another operation such as changing the size?

2023-01-10 10:53 UTC, fippo commented on index.bs
> +1. Run the [=generate key frame algorithm=] with |promise|, |this| and |rids|.
Done, three fell in one swoop ;-)

2023-01-26 15:30 UTC, youennf commented
I'll have a deeper look before next week editor's meeting.

2023-02-02 09:20 UTC, youennf commented
I had some more thoughts about this.
If the corresponding rid encoding is not active, or if sender is not sending at all (track is null or transceiver current direction is receive only), we probably want to reject.

We do not want to resolve the promise until this check is done, but this check will be done in parallel, close to the encoder for both requestKeyFrame variants. That removes the possibility for resolving the promise as soon as getting a key frame for one of the given rid in the transformer case. Or we would need to wait for the check result to actually start looking at key frames, which is probably not worth the extra work.

2023-02-02 09:21 UTC, youennf commented on index.bs
> +1. If the sender's transceiver kind is not `video`, reject |promise| with an {{OperationError}} and abort these steps.
NoSupportedError would be more adequate maybe?

2023-02-02 09:21 UTC, youennf commented on index.bs
> +    1. if |rid| is not associated with |sender|, reject Promise with an {{InvalidAccessError}} and abort these steps.
associated with is not really clear to me. Maybe we could reuse webrtc-pc terminology. something like `if sender's media stack is not configured with |rid| as active, `

I also think we should reject if the sender is not actively sending (its track is null or current direction does not include send). I am not exactly sure of which wording to use, maybe something like `if sender's media stack is not actively sending media`. 

It might also more accurate to queue a task to reject the Promise in the Promise realm event task loop, since all of those checks are done close to the encoder.

2023-02-02 09:21 UTC, youennf commented on index.bs
> +1. Instruct the encoder associated with |sender| to generate a key frame for |rids| or all layers when |rids| is empty.
We should make it clear that the promise gets resolved in the transformer context before any key frame triggered by this step is enqueued in the transformer readable stream. This PR is removing line 633-635 which was a similar statement with stronger-but-no-longer-valid guarantees.

2025-08-01 16:27 UTC, fippo commented
looking at https://www.w3.org/2023/05/16-webrtc-minutes.html#t04 this was superseeded by https://github.com/w3c/webrtc-extensions/pull/167 so closing. Feel free to reopen if this turns out to be a better starting point for changes here.

2025-08-01 16:27 UTC, closed without merging